version: "3"
services:
  webserver:
    build:
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty1!
    volumes:
      - mysql_eloquent:/var/lib/mysql
volumes:
  mysql_eloquent: